# Site settings
title: Gitanshu Munjal
email: grmunjal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Delhi, Davis, DIY
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://grmunjal.github.io" # the base hostname & protocol for your site

twitter_username: munjal_gitanshu
github_username:  grmunjal

# Build settings
markdown: kramdown
